### ISSUE TITLE
`grep -P` is highly experimental

### ISSUE THREAD

**Issue by andlrc** [seletskiy/zsh-favorite-directories#2]
`grep -P` is highly experimental, and can easily be avoided with `grep -E` which is POSIX:

```
grep -Pv '^\w+: $'
```

Can be substituted with:

```
grep -Ev '^[[:alnum:]]+: $'
```

**Comment by seletskiy** [comment]
@andlrc: I do not think it's makes any real change, because it's not performance bound. Also, I do not quite understand, what `experimental` means.

**Comment by andlrc** [comment]
Quoting[ `man grep` for GNU grep:](http://linux.die.net/man/1/grep)

```
   -P, --perl-regexp
      Interpret the  pattern  as  a  Perl-compatible  regular  expression
      (PCRE).   This  is  highly  experimental  and  grep  -P may warn of
      unimplemented features.
```

[`grep -P` is not supported by BSD Grep (OSX)](https://wiki.freebsd.org/BSDgrep) nor it is mentioned in POSIX Grep [(see `man 1p grep`)](http://www.unix.com/man-page/posix/1p/grep/)

**Comment by seletskiy** [comment]
@andlrc: Yes, but `man grep` do not explains, what `experimental` means. It only notes, that `-P` may warn about unimplemented features.

**Comment by andlrc** [comment]
I don't think you can find a list of what it means, but I can show you a bug fix involving `-P` and `-z`:

>   grep -Pz now diagnoses attempts to use patterns containing ^ and $, instead of mishandling these patterns.  This problem seems to be inherent to the PCRE API; removing this limitation is on PCRE's maint/README wish list.  Patterns can continue to match literal ^ and $ by escaping them with \ (now needed even inside [...]). [bug introduced in grep-2.5]

https://savannah.gnu.org/forum/forum.php?forum_id=8477

**Comment by andlrc** [comment]
One think I need to correct though is that `\w` matches a-z, A-Z, 0-9 and `_`. While `[:alnum:]` only matches a-z, A-Z and 0-9, using:

```
grep -Ev '^[[:alnum:]_]+: $'
```

should be a polyfill however.

**Comment by seletskiy** [comment]
@andlrc: I guess, better do not use grep at all. `-mindepth` is works as well.

**Comment by andlrc** [comment]
Just note that `-mindepth` is _not_ part of POSIX find, see `man 1p find`. This might not be a concern though, just worth mentioning.
